#!/usr/bin/env python3
"""Create a private, portable remote-deployment dotenv from a local dotenv.

The generated file is deliberately outside source control (``dist/`` is
ignored).  It copies only the selected provider credentials from an existing
private dotenv; no key is embedded in this script, README, or Git commit.

Run from the repository root, then transfer the generated file to the server
over an authenticated channel and rename it to ``.env`` beside the clone.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import os
import stat
import sys
from typing import Sequence


ROOT = Path(__file__).resolve().parents[1]
PUBLIC_VALUES = {
    "HCMAI_PUBLIC_INDEX_URL": "https://drive.google.com/drive/folders/1uqdS4qwOk4q-kbJGwSr2Mxj2G73qKoIE",
    "HCMAI_PUBLIC_KEYFRAMES_URL": "https://drive.google.com/drive/folders/10Tm99lilQxLGXBBrK_BHH58_KEir5ZhW",
    "HCMAI_PUBLIC_MODELS_URL": "https://drive.google.com/drive/folders/1rgNGKa003lvuvZX10bmSs7NiqXoK9cSV",
}
BASE_VALUES = {
    # All operational commands are run from the clone root.  Relative paths
    # keep the file portable across a new server username/home directory.
    "HCMAI_PYTHON": ".venv/bin/python",
    "HCMAI_PUBLIC_MODEL_ROOT": ".runtime/models",
    "HCMAI_PUBLIC_DOWNLOAD_ROOT": ".runtime/downloads",
    "HCMAI_PUBLIC_KEYFRAME_ARCHIVES": "keyframes-L21-L25.tar,keyframes-L26-L30.tar",
    "HCMAI_ACTIVE_VIDEO_PREFIXES": "L",
    "HCMAI_LOCAL_VLM_PATH": ".runtime/models/Qwen2.5-VL-7B-Instruct",
    "HCMAI_LOCAL_VLM_4BIT": "1",
    "VQA_MODALITY_MODEL_DIR": ".runtime/models/bge-m3",
    "VQA_MODALITY_ROUTING": "1",
    "HF_HOME": ".runtime/models/huggingface",
    "HF_HUB_CACHE": ".runtime/models/huggingface/hub",
    "HF_HUB_OFFLINE": "1",
    "TRANSFORMERS_OFFLINE": "1",
}
VLM_KEYS = ("VLM_BASE_URL", "VLM_API_KEY", "VLM_MODEL")
TEXT_KEYS = ("TEXT_BASE_URL", "TEXT_API_KEY", "TEXT_MODEL")
EMBEDDING_KEYS = ("EMBEDDING_BASE_URL", "EMBEDDING_API_KEY", "EMBEDDING_MODEL")
DEEPGRAM_KEYS = ("DEEPGRAM_API_KEY",)


class RemoteEnvError(RuntimeError):
    """The source secret configuration cannot produce a safe deployment file."""


def _load_dotenv(path: Path) -> dict[str, str]:
    if not path.is_file():
        raise RemoteEnvError(f"private dotenv does not exist: {path}")
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.removeprefix("export ").strip()
        value = value.strip()
        if len(value) >= 2 and value[:1] == value[-1:] and value[:1] in {"'", '"'}:
            value = value[1:-1]
        if key and value:
            values[key] = value
    return values


def _require(source: dict[str, str], keys: Sequence[str], *, label: str) -> dict[str, str]:
    missing = [key for key in keys if not source.get(key, "").strip()]
    if missing:
        raise RemoteEnvError(f"{label} is incomplete in source dotenv: {', '.join(missing)}")
    return {key: source[key] for key in keys}


def build_values(
    source: dict[str, str], *, answer_provider: str, include_text: bool,
    include_embedding: bool, include_deepgram: bool,
) -> dict[str, str]:
    values = {**BASE_VALUES, **PUBLIC_VALUES}
    if answer_provider == "openai":
        values["VQA_ANSWER_PROVIDER"] = "openai"
        values["HCMAI_EXECUTION_MODE"] = "production"
        values["HCMAI_NETWORK_MODE"] = "online"
        values.update(_require(source, VLM_KEYS, label="Lightning/OpenAI-compatible VLM"))
    elif answer_provider == "local":
        values["VQA_ANSWER_PROVIDER"] = "local"
        values["HCMAI_EXECUTION_MODE"] = "production"
        values["HCMAI_NETWORK_MODE"] = "offline"
    else:  # pragma: no cover - argparse prevents this
        raise RemoteEnvError(f"unsupported answer provider: {answer_provider}")
    if include_text:
        values.update(_require(source, TEXT_KEYS, label="text provider"))
    if include_embedding:
        values.update(_require(source, EMBEDDING_KEYS, label="embedding provider"))
    if include_deepgram:
        values.update(_require(source, DEEPGRAM_KEYS, label="Deepgram"))
    return values


def _render(values: dict[str, str]) -> str:
    if any("\n" in value or "\r" in value for value in values.values()):
        raise RemoteEnvError("dotenv values must be single-line")
    header = (
        "# Private generated deployment configuration. Do not commit or upload publicly.\n"
        "# Generated by scripts/export_remote_env.py.\n"
    )
    return header + "".join(f"{key}={values[key]}\n" for key in sorted(values))


def export_remote_env(
    source_path: Path, output_path: Path, *, answer_provider: str,
    include_text: bool = False, include_embedding: bool = False,
    include_deepgram: bool = False,
) -> tuple[Path, tuple[str, ...]]:
    source_path = source_path.resolve()
    output_path = output_path.resolve()
    if source_path == output_path:
        raise RemoteEnvError("refusing to overwrite the source private dotenv")
    values = build_values(
        _load_dotenv(source_path), answer_provider=answer_provider,
        include_text=include_text, include_embedding=include_embedding,
        include_deepgram=include_deepgram,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_render(values), encoding="utf-8")
    os.chmod(output_path, stat.S_IRUSR | stat.S_IWUSR)
    return output_path, tuple(sorted(values))


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=ROOT / ".env")
    parser.add_argument("--output", type=Path, default=ROOT / "dist" / "hcmai-remote.env")
    parser.add_argument("--answer-provider", choices=("openai", "local"), default="openai")
    parser.add_argument("--include-text", action="store_true")
    parser.add_argument("--include-embedding", action="store_true")
    parser.add_argument("--include-deepgram", action="store_true")
    args = parser.parse_args(argv)
    try:
        path, names = export_remote_env(
            args.source, args.output, answer_provider=args.answer_provider,
            include_text=args.include_text, include_embedding=args.include_embedding,
            include_deepgram=args.include_deepgram,
        )
    except RemoteEnvError as exc:
        print(f"remote dotenv export failed: {exc}", file=sys.stderr)
        return 2
    print(f"wrote private deployment dotenv: {path}")
    print("configured variables: " + ", ".join(names))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
